FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends openssh-client sshpass curl && \
    rm -rf /var/lib/apt/lists/*

# Optionally set an entrypoint if needed
ENTRYPOINT ["/bin/sh", "-c"]
