jobs:
  - name: fastp-trimming
    type: k8s
    jobSpec:
      container:
        image: quay.io/biocontainers/fastp:0.23.1--h79da9fb_0
        command: ["sh", "-c"]
        args:
          - |
            mkdir -p /out && \
            fastp \
              -i /data/sample_R1.fastq.gz \
              -I /data/sample_R2.fastq.gz \
              -o /out/sample_R1.trimmed.fastq.gz \
              -O /out/sample_R2.trimmed.fastq.gz \
              -h /out/trim_report.html
      inputs:
        artifacts:
          - name: inputArtifact
            path: /data
            s3:
              key: GenomicData
            archive:
              none: { }
      outputs:
        artifacts:
          - name: outputArtifact
            path: /out
            s3:
              key: GenomicDataAris
            archive:
              none: { }  

  - name: Alignment
    type: slurm
    command: "sbatch QC-Alignment.slurm"
    inputs:
      - from: fastp-trimming
        value: GenomicDataAris
    outputs:
      - name: fetchData
        value: true
      - name: outputFileName
        value: Genomic-QC-Alignment.out
      - name: outputFilePath
        value: slurm-out