jobs:
  - name: gen-epochs
    type: k8s
    jobSpec:
      script:
        image: python:alpine3.6
        command:
          - python
        source: |
          import random
          print(60000//random.randint(40000, 40000))

  - name: model-training
    type: slurm
    # command: "srun python3 distributed-mnist.py --lr=0.017 --epochs={{tasks.gen-epochs.outputs.result}} --batch-size=16 --log-path=mnist.log"
    # command: "export LR=${trialParameters.learningRate} && export epochs={{tasks.gen-epochs.outputs.result}} && sbatch katib-train.slurm"
    command: "export LR=0.017 && export epochs={{tasks.gen-epochs.outputs.result}} && sbatch katib-train.slurm"
    inputs:
      - value: data
      - from: gen-epochs
    outputs:
      - name: outputFileName
        value: mnist.log
      - name: outputFilePath
        value: slurm-out

  - name: print-message-from-slurm-output
    type: k8s
    jobSpec:
      inputs:
        artifacts:
        # unpack the message input artifact
        # and put it at /tmp/message
        - name: message
          path: /tmp/message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["cat /tmp/message/mnist.log"] 
    inputs:
      - name: message
        from: model-training         