apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hybrid-workflow-
spec:
  entrypoint: hybrid-workflow
  templates:
  - dag:
      tasks:
      - name: gen-epochs
        template: gen-epochs-template
      - arguments:
          parameters:
          - name: command
            value: export LR=${trialParameters.learningRate} && export epochs={{tasks.gen-epochs.outputs.result}}
              && sbatch katib-train.slurm
          - name: fetchData
            value: true
          - name: outputFileName
            value: mnist.log
          - name: outputFilePath
            value: slurm-out
          - name: s3artifact
            value: data
        dependencies:
        - gen-epochs
        name: model-training
        templateRef:
          name: slurm-template
          template: slurm-submit-job
    name: hybrid-workflow
  - name: gen-epochs-template
    script:
      command:
      - python
      image: python:alpine3.6
      source: 'import random

        print(60000//random.randint(40000, 40000))

        '
