apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"argo-server","namespace":"argo"},"spec":{"ports":[{"name":"web","port":2746,"targetPort":2746,"nodePort":32746}],"selector":{"app":"argo-server"},"type":"NodePort"}}
spec:
  type: NodePort
  selector:
    app: argo-server
  ports:
  - name: web
    port: 2746
    targetPort: 2746
    nodePort: 32746  # Optional: remove this line to let Kubernetes assign one automatically.
