apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: slurm-template
spec:
  entrypoint: slurm-submit-job
  templates:
    - name: slurm-submit-job
      inputs:
        parameters:
        - name: command
        - name: s3artifact
          default: "NotSet"    
        - name: slurmInput
          default: "NotSet"           
        - name: outputFileName
          default: "NotSet"
        - name: outputFilePath
          default: "NotSet"
      steps:
      - - name: trigger
          template: trigger-job
          arguments:
            parameters:
            - name: command
              value: "{{inputs.parameters.command}}"
            - name: s3artifact
              value: "{{inputs.parameters.s3artifact}}"
            - name: outputFileName
              value: "{{inputs.parameters.outputFileName}}"
            - name: outputFilePath
              value: "{{inputs.parameters.outputFilePath}}"
            - name: slurmInput
              value: "{{inputs.parameters.slurmInput}}"
      outputs:
        artifacts:
          - name: output-artifact
            from: "{{steps.trigger.outputs.artifacts.output-artifact}}"

    - name: trigger-job
      metadata:
        labels:
          katib.kubeflow.org/model-training: "true"
      inputs:
        artifacts:
          - name: input-artifact
            path: /tmp/
            optional: true
            s3:
              key: "{{inputs.parameters.s3artifact}}"
        parameters:
        - name: command
        - name: s3artifact
        - name: outputFileName
        - name: outputFilePath
        - name: slurmInput
      outputs:
        artifacts:
          - name: output-artifact
            path: "{{inputs.parameters.outputFilePath}}/"
            optional: true
            s3:
              key: "{{workflow.uid}}/{{inputs.parameters.outputFileName}}"
            archive:
              none: { }
        parameters: 
        - name: output-path
          valueFrom:
            path: /slurm-job-path
      container:
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COMMAND
            value: "{{inputs.parameters.command}}"
          - name: TRANSFER_DATA
            value: "{{inputs.parameters.s3artifact}}"
          - name: FILE_NAME
            value: "{{inputs.parameters.outputFileName}}"
          - name: FILE_PATH
            value: "{{inputs.parameters.outputFilePath}}"
          - name: SLURM_INPUT
            value: "{{inputs.parameters.slurmInput}}"
        image: my-ssh-client:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/trigger-job.sh"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

    - name: wait
      inputs:
        parameters:
          - name: job_id
      suspend: {}
