apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ssh-client-template
spec:
  entrypoint: ssh-client
  templates:
  - name: ssh-client
    inputs:
      parameters:
      - name: command
    container:
      image: ubuntu:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          apt-get update && \
          apt-get install -y openssh-client sshpass && \
          sshpass -p 'root' ssh -o StrictHostKeyChecking=no root@host.minikube.internal -p 2222 '{{inputs.parameters.command}} && echo "SSH Connection Successful!"'
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"
