apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: slurm-template
spec:
  entrypoint: slurm-submit-job
  templates:
    - name: slurm-submit-job
      inputs:
        parameters:
        - name: command
        - name: s3artifact
          default: "NotSet"        
        # - name: fileName
        #   default: "NotSet"
        # - name: filePath
        #   default: "NotSet"
      steps:
      - - name: trigger
          template: trigger-job
          arguments:
            parameters:
            - name: command
              value: "{{inputs.parameters.command}}"
            - name: s3artifact
              value: "{{inputs.parameters.s3artifact}}"
            # - name: fileName
            #   value: "{{inputs.parameters.fileName}}"
            # - name: filePath
            #   value: "{{inputs.parameters.filePath}}"
      # - - name: wait
      #     template: wait
      #     arguments:
      #       parameters:
      #         - name: job_id
      #           valueFrom:
      #             fieldRef:
      #               fieldPath: steps.trigger-job.metadata.name

    - name: trigger-job
      metadata:
        labels:
          katib.kubeflow.org/model-training: "true"
      inputs:
        artifacts:
          - name: input-artifact
            path: /tmp/
            optional: true
            s3:
              key: "{{inputs.parameters.s3artifact}}"
        parameters:
        - name: command
        - name: s3artifact
        # - name: fileName
        #   default: "NotSet"
        # - name: filePath
        #   default: "NotSet"
      container:
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COMMAND
            value: "{{inputs.parameters.command}}"
          - name: TRANSFER_DATA
            value: "{{inputs.parameters.s3artifact}}"
          # - name: FILE_NAME
          #   value: "{{inputs.parameters.fileName}}"
          # - name: FILE_PATH
          #   value: "{{inputs.parameters.filePath}}"  
        image: my-ssh-client:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/local/bin/trigger-job.sh"]   
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"

    - name: wait
      inputs:
        parameters:
          - name: job_id
      suspend: {}
