apiVersion: v1
kind: Pod
metadata:
  name: ssh-client-pod
spec:
  containers:
  - name: ssh-client-container
    image: docker.io/kubeflowkatib/pytorch-mnist-cpu:latest
    command: ["/bin/sh", "-c"]
    args:
      - apt-get update && apt-get install -y openssh-client && sleep infinity
    resources:
      requests:
        memory: "128Mi"   # Request 128 MiB of memory
        cpu: "100m"       # Request 0.1 vCPU
      limits:
        memory: "256Mi"   # Limit to 256 MiB of memory
        cpu: "500m"       # Limit to 0.5 vCPU
  restartPolicy: Never
