apiVersion: v1
kind: Service
metadata:
  name: ssh-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
      nodePort: 32222  # NodePort range in Minikube is usually 30000-32767
