apiVersion: v1
kind: Pod
metadata:
  name: ssh-test-pod
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: ssh-client
    image: linuxserver/openssh-server
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    stdin: true
    tty: true
  restartPolicy: Never
