---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-manager
  namespace: argo
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["get", "list", "watch", "resume", "stop"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-manager-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: slurm
  namespace: argo
roleRef:
  kind: Role
  name: argo-workflow-manager
  apiGroup: rbac.authorization.k8s.io
