jobs:
  - name: gen-epochs
    type: k8s
    jobSpec:
      script:
        image: python:alpine3.6
        command:
          - python
        source: |
          import random
          print(60000//random.randint(40000, 40000))     

  - name: model-training
    type: slurm
    command: "export LR=0.017 && export epochs={{tasks.gen-epochs.outputs.result}} && sbatch katib-train-local.slurm"
    inputs:
      - s3key: Mnist-Dataset
      - from: gen-epochs
    outputs:
      - name: outputFileName
        value: mnist.log

  - name: model-training2
    type: slurm
    command: "export LR=0.017 && export epochs={{tasks.gen-epochs.outputs.result}} && sbatch katib-train-local.slurm"
    inputs:
      - s3key: Mnist-Dataset
      - from: gen-epochs
    outputs:
      - name: outputFileName
        value: mnist.log

  - name: model-training3
    type: slurm
    command: "export LR=0.017 && export epochs={{tasks.gen-epochs.outputs.result}} && sbatch katib-train-local.slurm"
    inputs:
      - s3key: Mnist-Dataset
      - from: gen-epochs
    outputs:
      - name: outputFileName
        value: mnist.log

  - name: model-training4
    type: slurm
    command: "export LR=0.017 && export epochs={{tasks.gen-epochs.outputs.result}} && sbatch katib-train-local.slurm"
    inputs:
      - s3key: Mnist-Dataset
      - from: gen-epochs
    outputs:
      - name: outputFileName
        value: mnist.log