apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hybrid-workflow-
spec:
  entrypoint: hybrid-workflow
  templates:
  - dag:
      tasks:
      - name: gen-epochs
        template: gen-epochs-template
      - arguments:
          parameters:
          - name: command
            value: export LR=${trialParameters.learningRate} && export epochs={{tasks.gen-epochs.outputs.result}}
              && sbatch katib-train.slurm
          - name: outputFileName
            value: mnist.log
          - name: fetchData
            value: 'true'
          - name: s3artifact
            value: Mnist-Dataset
        dependencies:
        - gen-epochs
        name: model-training
        templateRef:
          clusterScope: true
          name: slurm-template
          template: slurm-submit-job
      - arguments:
          artifacts:
          - from: '{{tasks.model-training.outputs.artifacts.output-artifact}}'
            name: logs
        dependencies:
        - model-training
        name: print-message-from-slurm-output
        template: print-message-from-slurm-output-template
    name: hybrid-workflow
  - name: gen-epochs-template
    script:
      command:
      - python
      image: python:alpine3.6
      source: 'import random

        print(60000//random.randint(40000, 40000))

        '
  - container:
      args:
      - sleep 5;cat /tmp/logs/mnist.log;cp /tmp/logs/mnist.log /katib/mnist.log
      command:
      - sh
      - -c
      image: busybox:latest
    inputs:
      artifacts:
      - name: logs
        path: /tmp/logs
    metadata:
      labels:
        katib.kubeflow.org/model-training: 'true'
    name: print-message-from-slurm-output-template
